version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: TaskDB
      MYSQL_USER: springuser
      MYSQL_PASSWORD: springpass
    ports:
      - "3307:3306"
    networks:
      - tasknet

  app:
    build: .
    container_name: task_management_app
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/TaskDB
      SPRING_DATASOURCE_USERNAME: springuser
      SPRING_DATASOURCE_PASSWORD: springpass
    networks:
      - tasknet

  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: gitlab.local
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8181'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - "8181:80"   # GitLab web UI
      - "2224:22"     # GitLab SSH for git push/pull
    networks:
      - tasknet
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab

#  jenkins:
#    image: jenkins/jenkins:lts
#    container_name: jenkins
#    restart: always
#    user: root
#    ports:
#      - "8080:8080"   # Jenkins web UI
#      - "50000:50000" # Jenkins agent
#    networks:
#      - tasknet
#    volumes:
#      - jenkins-data:/var/jenkins_home
#      - /var/run/docker.sock:/var/run/docker.sock

networks:
  tasknet:

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  jenkins-data:
