apiVersion: v1
kind: Service
metadata:
  name: taskmanagement-service
spec:
  type: NodePort
  selector:
    app: taskmanagement
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
